//// <auto-generated />
//using System;
//using EndSickness.Persistance.EndSicknessDb;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace EndSickness.Persistance.Migrations
//{
//    [DbContext(typeof(EndSicknessContext))]
//    [Migration("20230412105330_RefactorUserId")]
//    partial class RefactorUserId
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.15")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("EndSickness.Domain.Entities.Medicine", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<TimeSpan>("Cooldown")
//                        .HasColumnType("time");

//                    b.Property<int?>("MaxDailyAmount")
//                        .HasColumnType("int");

//                    b.Property<int?>("MaxDaysOfTreatment")
//                        .HasColumnType("int");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .ValueGeneratedOnAdd()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)")
//                        .HasDefaultValue("");

//                    b.Property<string>("OwnerId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("StatusId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasDefaultValue(1);

//                    b.HasKey("Id");

//                    b.ToTable("Medicines");
//                });

//            modelBuilder.Entity("EndSickness.Domain.Entities.MedicineLog", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<DateTime>("LastlyTaken")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("MedicineId")
//                        .HasColumnType("int");

//                    b.Property<string>("OwnerId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("StatusId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("MedicineId");

//                    b.ToTable("MedicineLogs");
//                });

//            modelBuilder.Entity("EndSickness.Domain.Entities.MedicineLog", b =>
//                {
//                    b.HasOne("EndSickness.Domain.Entities.Medicine", "Medicine")
//                        .WithMany()
//                        .HasForeignKey("MedicineId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Medicine");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
